// <auto-generated />
using System;
using Auth.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HsSqlAgent.PostgresMigrations.Auth
{
    [DbContext(typeof(AuthContext))]
    partial class AuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auth.Service.Data.Entites.AuthAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AuthActions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "view",
                            Name = "view"
                        },
                        new
                        {
                            Id = 2,
                            Code = "create",
                            Name = "create"
                        },
                        new
                        {
                            Id = 3,
                            Code = "edit",
                            Name = "edit"
                        },
                        new
                        {
                            Id = 4,
                            Code = "delete",
                            Name = "delete"
                        },
                        new
                        {
                            Id = 5,
                            Code = "revoke",
                            Name = "revoke"
                        });
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.MemberRole", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("MemberId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("MemberRoles");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Overview",
                            Path = "/home"
                        },
                        new
                        {
                            Id = 2,
                            Name = "MCP Keys",
                            Path = "/runtime/mcp-keys"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Custom Tools",
                            Path = "/runtime/custom-tools"
                        },
                        new
                        {
                            Id = 4,
                            Name = "DB Management",
                            Path = "/runtime/db-management"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Audit",
                            Path = "/runtime/audit"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Role Management",
                            Path = "/auth/role"
                        },
                        new
                        {
                            Id = 7,
                            Name = "User Management",
                            Path = "/auth/user"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Semantic Layer",
                            Path = "/runtime/db-management/semantic"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Security Policy",
                            Path = "/runtime/security"
                        });
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.PermissionAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId", "ActionId")
                        .IsUnique();

                    b.ToTable("PermissionActions");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.PermissionActionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("PermissionId", "ActionId")
                        .IsUnique();

                    b.ToTable("PermissionActionTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActionId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 3,
                            ActionId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 4,
                            ActionId = 5,
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 5,
                            ActionId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 6,
                            ActionId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 7,
                            ActionId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 8,
                            ActionId = 4,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 9,
                            ActionId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 10,
                            ActionId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 11,
                            ActionId = 3,
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 12,
                            ActionId = 4,
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 13,
                            ActionId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 14,
                            ActionId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 15,
                            ActionId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 16,
                            ActionId = 3,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 17,
                            ActionId = 4,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 18,
                            ActionId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 19,
                            ActionId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 20,
                            ActionId = 3,
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 21,
                            ActionId = 4,
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 22,
                            ActionId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 23,
                            ActionId = 3,
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 24,
                            ActionId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 25,
                            ActionId = 3,
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 26,
                            ActionId = 3,
                            PermissionId = 2
                        });
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.TokenBlacklistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.ToTable("TokenBlacklistEntries");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.MemberRole", b =>
                {
                    b.HasOne("Auth.Service.Data.Entites.Member", "Member")
                        .WithMany("MemberRoles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Service.Data.Entites.Role", "Role")
                        .WithMany("MemberRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.PermissionAction", b =>
                {
                    b.HasOne("Auth.Service.Data.Entites.AuthAction", "Action")
                        .WithMany("PermissionActions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Service.Data.Entites.Permission", "Permission")
                        .WithMany("PermissionActions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Service.Data.Entites.Role", "Role")
                        .WithMany("PermissionActions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.PermissionActionTemplate", b =>
                {
                    b.HasOne("Auth.Service.Data.Entites.AuthAction", "Action")
                        .WithMany("PermissionActionTemplates")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Service.Data.Entites.Permission", "Permission")
                        .WithMany("PermissionActionTemplates")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.AuthAction", b =>
                {
                    b.Navigation("PermissionActionTemplates");

                    b.Navigation("PermissionActions");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.Member", b =>
                {
                    b.Navigation("MemberRoles");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.Permission", b =>
                {
                    b.Navigation("PermissionActionTemplates");

                    b.Navigation("PermissionActions");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.Role", b =>
                {
                    b.Navigation("MemberRoles");

                    b.Navigation("PermissionActions");
                });
#pragma warning restore 612, 618
        }
    }
}
