using System.Text.Json;
using DotNet.Testcontainers.Builders;
using FirebirdSql.Data.FirebirdClient;
using Microsoft.Extensions.Configuration;
using Moq;
using SqlAgent.Service.Enums;
using SqlAgent.Service.Interfaces;
using SqlAgent.Service.Models;
using SqlAgent.Service.Services;
using SqlAgent.Service.Strategies;
using Testcontainers.FirebirdSql;
using Xunit;

namespace SqlAgent.Test.Strategies;

public class FirebirdFixture : IDbFixture
{
    public FirebirdSqlContainer Container { get; }
    public string ConnectionString => Container.GetConnectionString();

    public FirebirdFixture()
    {
        Container = new FirebirdSqlBuilder("jacobalberty/firebird:v5.0")
            .WithPassword("masterkey")
            .Build();
    }

    public async ValueTask InitializeAsync()
    {
        await Container.StartAsync();

        var strategy = new FirebirdStrategy(new QueryValueParserService(), new Mock<IConfiguration>().Object);
        await using var conn = strategy.CreateConnection(ConnectionString);
        await conn.OpenAsync();
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = @"
            CREATE TABLE USERS (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NAME VARCHAR(100),
                AGE INTEGER,
                ACTIVE BOOLEAN,
                CREATED_DATE TIMESTAMP
            )
        ";
        await cmd.ExecuteNonQueryAsync();

        cmd.CommandText = "INSERT INTO USERS (NAME, AGE, ACTIVE, CREATED_DATE) VALUES ('Alice', 30, TRUE, TIMESTAMP '2023-01-01 10:00:00')";
        await cmd.ExecuteNonQueryAsync();
        cmd.CommandText = "INSERT INTO USERS (NAME, AGE, ACTIVE, CREATED_DATE) VALUES ('Bob', 25, TRUE, TIMESTAMP '2023-02-01 10:00:00')";
        await cmd.ExecuteNonQueryAsync();
        cmd.CommandText = "INSERT INTO USERS (NAME, AGE, ACTIVE, CREATED_DATE) VALUES ('Charlie', 35, FALSE, TIMESTAMP '2023-03-01 10:00:00')";
        await cmd.ExecuteNonQueryAsync();

        cmd.CommandText = @"
            CREATE TABLE ORDERS (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                USER_ID INTEGER,
                AMOUNT DECIMAL(10,2),
                ORDER_DATE DATE
            )
        ";
        await cmd.ExecuteNonQueryAsync();
        cmd.CommandText = "INSERT INTO ORDERS (USER_ID, AMOUNT, ORDER_DATE) VALUES (1, 150.0, DATE '2023-01-10')";
        await cmd.ExecuteNonQueryAsync();
        cmd.CommandText = "INSERT INTO ORDERS (USER_ID, AMOUNT, ORDER_DATE) VALUES (1, 200.0, DATE '2023-02-15')";
        await cmd.ExecuteNonQueryAsync();
        cmd.CommandText = "INSERT INTO ORDERS (USER_ID, AMOUNT, ORDER_DATE) VALUES (2, 50.0, DATE '2023-03-20')";
        await cmd.ExecuteNonQueryAsync();

        cmd.CommandText = @"
            CREATE TABLE ORDER_DETAILS (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                UNIT_PRICE DOUBLE PRECISION,
                QUANTITY INTEGER,
                DISCOUNT DOUBLE PRECISION
            )
        ";
        await cmd.ExecuteNonQueryAsync();
        cmd.CommandText = "INSERT INTO ORDER_DETAILS (UNIT_PRICE, QUANTITY, DISCOUNT) VALUES (10.123, 2, 0.1)";
        await cmd.ExecuteNonQueryAsync();
        cmd.CommandText = "INSERT INTO ORDER_DETAILS (UNIT_PRICE, QUANTITY, DISCOUNT) VALUES (20.456, 1, 0.05)";
        await cmd.ExecuteNonQueryAsync();
    }

    public async ValueTask DisposeAsync()
    {
        await Container.DisposeAsync();
    }
}


public class FirebirdStrategyTests(FirebirdFixture fixture) : BaseStrategyTests<FirebirdStrategy, FirebirdFixture>(fixture)
{
    protected override bool SupportsOffsetTimestamp => false;
    protected override bool SupportsPortableDateFormatting => false;
    protected override bool SupportsFormattedDateParsing => false;
    protected override FirebirdStrategy CreateStrategy(IQueryValueParserService parser, IConfiguration configuration)
        => new(parser, configuration);

    protected override string TestTableName => "USERS";
    protected override string TestOrdersTableName => "ORDERS";
    protected override string TestOrderDetailsTableName => "ORDER_DETAILS";
    protected override string TestOrderDetailsUnitPriceColumn => "UNIT_PRICE";
    protected override string TestOrderDetailsQuantityColumn => "QUANTITY";
    protected override string TestOrderDetailsDiscountColumn => "DISCOUNT";
    protected override string TestSchemaName => "Default";
    protected override string TestOrdersUserIdColumn => "USER_ID";
    protected override string TestOrdersIdColumn => "ID";
    protected override string TestOrderDateColumn => "ORDER_DATE";
    protected override int TestFirstOrderId => 101;
    protected override string TestUserIdColumn => "ID";
    protected override string TestUserNameColumn => "NAME";

    // Firebird returns SQL code -204 for table-not-found and -206 for column-not-found errors.
    protected override string TableNotFoundErrorCode => "FB_SQL_-204";
    protected override string ColumnNotFoundErrorCode => "FB_SQL_-206";

    // Firebird uppercases unquoted identifiers, so result properties are UPPERCASE.
    private const string PropUname = "UNAME";
    private const string PropAge = "AGE";
    private const string PropUid = "UID";
    private const string PropOrderCount = "ORDER_COUNT";
    private const string PropUserType = "USER_TYPE";

    [Fact]
    public override async Task ExecuteQueryAsync_ShouldReturnDbError_WhenTableNotFound()
    {
        var ex = await Assert.ThrowsAsync<Exception>(() => Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                TableName = "NON_EXISTENT"
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken));
        Assert.Contains("code=FB_SQL_-204", ex.Message);
    }

    [Fact]
    public override async Task ExecuteQueryAsync_ShouldReturnDbError_WhenColumnNotFound()
    {
        var ex = await Assert.ThrowsAsync<Exception>(() => Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                TableName = TestTableName,
                SelectColumns = [new FieldSelectCondition { FieldName = "NON_EXISTENT_COL_HS" }]
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken));
        Assert.Contains("code=FB_SQL_-206", ex.Message);
    }

    [Fact]
    public void BuildConnectionString_ShouldGenerateValidFirebirdFormat()
    {
        var model = new BuildDbConnectionModel
        {
            Provider = "Firebird",
            Host = "localhost",
            Port = "3050",
            Database = "/path/to/db.fdb",
            Username = "sysdba",
            Password = "pw"
        };
        var connStr = Strategy.BuildConnectionString(model);

        Assert.Contains("data source=localhost", connStr, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("port number=3050", connStr, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("user id=sysdba", connStr, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public override async Task ExecuteQueryAsync_ShouldSupportOffsetWithoutLimit()
    {
        var json = await Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                TableName = TestTableName,
                SelectColumns =
                [
                    new FieldSelectCondition { FieldName = "NAME", Alias = "uname" }
                ],
                OrderByColumns =
                [
                    new FieldOrderByCondition { FieldName = "NAME", Direction = SortDirection.Asc }
                ],
                Limit = 10,
                Offset = 1
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);

        var rows = JsonSerializer.Deserialize<List<JsonElement>>(json);
        Assert.NotNull(rows);
        Assert.Equal(2, rows.Count);
        // Firebird uppercases unquoted aliases
        Assert.Equal("Bob", rows[0].GetProperty(PropUname).GetString());
    }

    [Fact]
    public override async Task ExecuteQueryAsync_ShouldSupportFullQueryDefinitionStructure()
    {
        var json = await Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                Alias = "u",
                TableName = TestTableName,
                Joins =
                [
                    new JoinCondition
                    {
                        Table = TestOrdersTableName,
                        Alias = "o",
                        Type = JoinType.Left,
                        OnConditions =
                        [
                            new ColumnCompareWhereCondition
                            {
                                LeftFieldName = "u.ID",
                                Operator = "=",
                                RightFieldName = "o.USER_ID"
                            }
                        ]
                    }
                ],
                SelectColumns =
                [
                    new FieldSelectCondition { FieldName = "u.ID", Alias = "uid" },
                    new FieldSelectCondition { FieldName = "u.NAME", Alias = "uname" },
                    new FunctionSelectCondition
                    {
                        FunctionName = "COUNT",
                        Arguments = [new FieldSelectCondition { FieldName = "o.ID" }],
                        Alias = "order_count"
                    },
                    new ConstantSelectCondition { Constant = "active_user", Alias = "user_type" }
                ],
                WhereColumnsAndValues =
                [
                    new GroupWhereCondition
                    {
                        Groups =
                        [
                            new BasicWhereCondition { FieldName = "o.AMOUNT", Operator = ">", Value = 0 },
                            new BasicWhereCondition { FieldName = "o.ID", Operator = "isnull", Value = null, IsOr = true }
                        ]
                    }
                ],
                GroupByConditions =
                [
                    new FieldGroupByCondition { FieldName = "u.ID" },
                    new FieldGroupByCondition { FieldName = "u.NAME" }
                ],
                HavingConditions =
                [
                    new FunctionHavingCondition
                    {
                        LeftFunction = new SqlFunctionCondition
                        {
                            FunctionName = "COUNT",
                            Arguments = [new FieldSelectCondition { FieldName = "o.ID" }]
                        },
                        Operator = ">=",
                        Value = 0
                    }
                ],
                OrderByColumns =
                [
                    new FieldOrderByCondition { FieldName = "u.ID", Direction = SortDirection.Asc }
                ],
                Limit = 5
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);

        var rows = JsonSerializer.Deserialize<List<JsonElement>>(json);
        Assert.NotNull(rows);
        Assert.NotEmpty(rows);
        Assert.True(rows.Count <= 5);

        foreach (var row in rows)
        {
            Assert.True(row.TryGetProperty(PropUid, out _));
            Assert.True(row.TryGetProperty(PropUname, out _));
            Assert.True(row.TryGetProperty(PropOrderCount, out _));
            Assert.True(row.TryGetProperty(PropUserType, out _));
        }
    }

    [Fact]
    public override async Task ExecuteQueryAsync_ShouldSupportExistsSubQueryWhereCondition()
    {
        var json = await Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                TableName = TestTableName,
                SelectColumns =
                [
                    new FieldSelectCondition { FieldName = "NAME", Alias = "uname" }
                ],
                WhereColumnsAndValues =
                [
                    new SubQueryWhereCondition
                    {
                        Operator = "EXISTS",
                        SubQuery = new QueryDefinition
                        {
                            TableName = TestOrdersTableName,
                            WhereColumnsAndValues =
                            [
                                new ColumnCompareWhereCondition
                                {
                                    LeftFieldName = "USER_ID",
                                    Operator = "=",
                                    RightFieldName = "USERS.ID"
                                }
                            ]
                        }
                    }
                ],
                OrderByColumns =
                [
                    new FieldOrderByCondition { FieldName = "NAME", Direction = SortDirection.Asc }
                ]
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);

        var rows = JsonSerializer.Deserialize<List<JsonElement>>(json);
        Assert.NotNull(rows);
        Assert.Equal(2, rows.Count);
        Assert.Equal("Alice", rows[0].GetProperty(PropUname).GetString());
        Assert.Equal("Bob", rows[1].GetProperty(PropUname).GetString());
    }

    [Fact]
    public override async Task ExecuteQueryAsync_ShouldSupportSubQuerySelectCondition()
    {
        var json = await Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                Alias = "u",
                TableName = TestTableName,
                SelectColumns =
                [
                    new FieldSelectCondition { FieldName = "u.NAME", Alias = "uname" },
                    new SubQuerySelectCondition
                    {
                        TableName = TestOrdersTableName,
                        SelectColumns =
                        [
                            new FunctionSelectCondition
                            {
                                FunctionName = "COUNT",
                                Arguments = [new FieldSelectCondition { FieldName = "ID" }]
                            }
                        ],
                        WhereColumnsAndValues =
                        [
                            new ColumnCompareWhereCondition
                            {
                                LeftFieldName = "USER_ID",
                                Operator = "=",
                                RightFieldName = "u.ID"
                            }
                        ],
                        Alias = "order_count"
                    }
                ],
                OrderByColumns =
                [
                    new FieldOrderByCondition { FieldName = "u.ID", Direction = SortDirection.Asc }
                ]
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);

        var rows = JsonSerializer.Deserialize<List<JsonElement>>(json);
        Assert.NotNull(rows);
        Assert.Equal(3, rows.Count);
        Assert.True(rows[0].TryGetProperty(PropOrderCount, out _));
    }

    [Fact]
    public override async Task ExecuteQueryAsync_ShouldSupportCaseExpression()
    {
        var json = await Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                TableName = TestTableName,
                SelectColumns =
                [
                    new CaseSelectCondition
                    {
                        Whens =
                        [
                            new CaseWhenCondition
                            {
                                Condition = new BasicWhereCondition
                                {
                                    FieldName = "AGE",
                                    Operator = ">=",
                                    Value = 30
                                },
                                Then = "senior"
                            }
                        ],
                        Else = "junior",
                        Alias = "age_group"
                    }
                ],
                Limit = 1
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);

        var rows = JsonSerializer.Deserialize<List<JsonElement>>(json);
        Assert.NotNull(rows);
        Assert.NotEmpty(rows);
    }

    [Fact]
    public override async Task ExecuteQueryAsync_ShouldSupportGroupWhereCondition()
    {
        var json = await Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                TableName = TestTableName,
                SelectColumns = [new FieldSelectCondition { FieldName = "NAME", Alias = "uname" }],
                WhereColumnsAndValues =
                [
                    new GroupWhereCondition
                    {
                        Groups =
                        [
                            new BasicWhereCondition { FieldName = "AGE", Operator = ">=", Value = 30 },
                            new BasicWhereCondition { FieldName = "ACTIVE", Operator = "=", Value = true, IsOr = true }
                        ]
                    }
                ],
                OrderByColumns = [new FieldOrderByCondition { FieldName = "NAME", Direction = SortDirection.Asc }]
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);

        var rows = JsonSerializer.Deserialize<List<JsonElement>>(json);
        Assert.NotNull(rows);
        Assert.Equal(3, rows.Count);
    }

    [Fact]
    public override async Task ExecuteQueryAsync_ShouldSupportBetweenOperator()
    {
        var json = await Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                TableName = TestTableName,
                SelectColumns = [new FieldSelectCondition { FieldName = "NAME", Alias = "uname" }],
                WhereColumnsAndValues =
                [
                    new BasicWhereCondition { FieldName = "AGE", Operator = "between", Value = new object[] { 25, 35 } }
                ],
                OrderByColumns =
                [
                    new FieldOrderByCondition { FieldName = "NAME", Direction = SortDirection.Asc }
                ]
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);

        var rows = JsonSerializer.Deserialize<List<JsonElement>>(json);
        Assert.NotNull(rows);
        Assert.Equal(3, rows.Count);
    }

    [Fact]
    public override async Task ExecuteQueryAsync_ShouldSupportWhereNotIsOrIsNot()
    {
        var json = await Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                TableName = TestTableName,
                SelectColumns =
                [
                    new FieldSelectCondition { FieldName = "NAME", Alias = "uname" }
                ],
                WhereColumnsAndValues =
                [
                    new BasicWhereCondition { FieldName = "NAME", Operator = "=", Value = "Alice" },
                    new BasicWhereCondition { FieldName = "NAME", Operator = "=", Value = "Bob", IsOr = true },
                    new BasicWhereCondition { FieldName = "NAME", Operator = "LIKE", Value = "C%", IsNot = true }
                ],
                OrderByColumns =
                [
                    new FieldOrderByCondition { FieldName = "NAME", Direction = SortDirection.Asc }
                ]
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);

        var rows = JsonSerializer.Deserialize<List<JsonElement>>(json);
        Assert.NotNull(rows);
        Assert.Equal(2, rows.Count);
    }

    [Fact]
    public override async Task ExecuteQueryAsync_ShouldSupportStringAggregateFunction()
    {
        var json = await Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                TableName = TestTableName,
                SelectColumns =
                [
                    new FunctionSelectCondition
                    {
                        FunctionName = "STRING_AGG",
                        Arguments =
                        [
                            new FieldSelectCondition { FieldName = "NAME" },
                            new ConstantSelectCondition { Constant = "," }
                        ],
                        Alias = "names"
                    }
                ]
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);

        var rows = JsonSerializer.Deserialize<List<JsonElement>>(json);
        Assert.NotNull(rows);
        Assert.NotEmpty(rows);
    }

    [Fact]
    public override async Task ExecuteQueryAsync_ShouldSupportRoundFunction()
    {
        var json = await Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                TableName = TestOrderDetailsTableName,
                SelectColumns =
                [
                    new FunctionSelectCondition
                    {
                        FunctionName = "ROUND",
                        Arguments =
                        [
                            new FieldSelectCondition { FieldName = TestOrderDetailsUnitPriceColumn },
                            new ConstantSelectCondition { Constant = 2 }
                        ],
                        Alias = "rounded"
                    }
                ],
                Limit = 1
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);

        Assert.NotEqual("[]", json);
    }

    [Fact]
    public async Task ExecuteQueryAsync_ShouldSupportDateDiffDay()
    {
        var definition = SqlDefinitionParser.ParseQuery(
            $"SELECT DATEDIFF(DAY, DATE '2023-01-01', DATE '2023-01-03') AS D FROM {TestTableName}");
        definition.Limit = 1;
        var json = await Strategy.ExecuteQueryAsync(
            definition,
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);
        using var document = JsonDocument.Parse(json);
        Assert.Equal(2, document.RootElement[0].EnumerateObject().Single().Value.GetInt32());
    }

    [Fact]
    public async Task ExecuteQueryAsync_ShouldSupportDatePartYear()
    {
        var definition = SqlDefinitionParser.ParseQuery(
            $"SELECT YEAR(CREATED_DATE) AS Y FROM {TestTableName}");
        definition.Limit = 1;
        var json = await Strategy.ExecuteQueryAsync(
            definition,
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);
        using var document = JsonDocument.Parse(json);
        Assert.Equal(2023, document.RootElement[0].EnumerateObject().Single().Value.GetInt32());
    }

    [Fact]
    public async Task ExecuteQueryAsync_ShouldSupportDateAddDay()
    {
        var definition = SqlDefinitionParser.ParseQuery(
            $"SELECT DATEADD(DAY, 2, DATE '2023-01-01') AS D FROM {TestTableName}");
        definition.Limit = 1;
        var json = await Strategy.ExecuteQueryAsync(
            definition,
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);
        Assert.NotEqual("[]", json);
    }

    [Fact]
    public async Task ExecuteQueryAsync_ShouldSupportCurrentDate()
    {
        var definition = SqlDefinitionParser.ParseQuery(
            $"SELECT CURRENT_DATE AS D FROM {TestTableName}");
        definition.Limit = 1;
        var json = await Strategy.ExecuteQueryAsync(
            definition,
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);
        Assert.NotEqual("[]", json);
    }

    [Fact]
    public async Task ExecuteQueryAsync_ShouldSupportBooleanConstant()
    {
        var json = await Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                TableName = TestTableName,
                SelectColumns = [new ConstantSelectCondition { Constant = true, Alias = "b" }],
                Limit = 1
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);
        Assert.NotEqual("[]", json);
    }

    [Fact]
    public async Task ExecuteQueryAsync_ShouldSupportStringConstant()
    {
        var json = await Strategy.ExecuteQueryAsync(
            new QueryDefinition
            {
                TableName = TestTableName,
                SelectColumns = [new ConstantSelectCondition { Constant = "x", Alias = "s" }],
                Limit = 1
            },
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);
        Assert.NotEqual("[]", json);
    }

    [Fact]
    public async Task ExecuteQueryAsync_ShouldSupportNestedArithmetic()
    {
        var definition = SqlDefinitionParser.ParseQuery(
            $"SELECT ROUND((AGE * 1.25) + 2, 2) AS V FROM {TestTableName}");
        definition.Limit = 1;
        var json = await Strategy.ExecuteQueryAsync(
            definition,
            Fixture.ConnectionString,
            cancellationToken: TestContext.Current.CancellationToken);
        Assert.NotEqual("[]", json);
    }

    protected override DmlDefinition CreateInsertDml() => new()
    {
        Operation = DmlOperation.Insert,
        TableName = TestTableName,
        Values =
        [
            new NameValuePair { FieldName = "NAME", Value = "David" },
            new NameValuePair { FieldName = "AGE", Value = 40 },
            new NameValuePair { FieldName = "ACTIVE", Value = true }
        ]
    };
}
