using System.Text.Json;
using DotNet.Testcontainers.Builders;
using Microsoft.Extensions.Configuration;
using Moq;
using SqlAgent.Service.Interfaces;
using SqlAgent.Service.Models;
using SqlAgent.Service.Services;
using SqlAgent.Service.Strategies;
using Testcontainers.Oracle;
using Xunit;

namespace SqlAgent.Test.Strategies;

public class OracleFixture : IDbFixture
{
    public OracleContainer Container { get; }
    public string ConnectionString => Container.GetConnectionString();

    public OracleFixture()
    {
        Container = new OracleBuilder("gvenzl/oracle-xe:21.3.0-slim-faststart")
            .WithPassword("TestPass123!")
            .Build();
    }

    public async ValueTask InitializeAsync()
    {
        await Container.StartAsync();

        var strategy = new OracleStrategy(new QueryValueParserService(), new Mock<IConfiguration>().Object);
        using var conn = strategy.CreateConnection(ConnectionString);
        await conn.OpenAsync();
        using var cmd = conn.CreateCommand();
        // Oracle requires specific syntax for table creation
        cmd.CommandText = @"
            CREATE TABLE HS_USERS (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NAME VARCHAR2(100),
                AGE NUMBER,
                ACTIVE NUMBER(1),
                CREATED_DATE TIMESTAMP
            )
        ";
        await cmd.ExecuteNonQueryAsync();

        cmd.CommandText = "INSERT INTO HS_USERS (NAME, AGE, ACTIVE, CREATED_DATE) VALUES ('Alice', 30, 1, TIMESTAMP '2023-01-01 10:00:00')";
        await cmd.ExecuteNonQueryAsync();
        
        cmd.CommandText = "COMMIT";
        await cmd.ExecuteNonQueryAsync();
    }

    public async ValueTask DisposeAsync() => await Container.DisposeAsync();
}


public class OracleStrategyTests(OracleFixture fixture) : BaseStrategyTests<OracleStrategy, OracleFixture>(fixture)
{
    protected override OracleStrategy CreateStrategy(IQueryValueParserService parser, IConfiguration configuration) 
        => new OracleStrategy(parser, configuration);

    protected override string TestTableName => "HS_USERS";
    protected override string TestSchemaName => new Oracle.ManagedDataAccess.Client.OracleConnectionStringBuilder(Fixture.ConnectionString).UserID.ToUpper();

    protected override string TableNotFoundErrorCode => "ORA-00942";
    protected override string ColumnNotFoundErrorCode => "ORA-00904";

    [Fact]
    public override async Task GetColumnsAsync_ShouldReturnColumnTypes()
    {
        await base.GetColumnsAsync_ShouldReturnColumnTypes();
        var columns = await Strategy.GetColumnsAsync(Fixture.ConnectionString, TestSchemaName, TestTableName, TestContext.Current.CancellationToken);
        Assert.Contains(columns, c => c.Column == "ID" && c.Type.Contains("NUMBER", StringComparison.OrdinalIgnoreCase));
        Assert.Contains(columns, c => c.Column == "NAME" && c.Type.Contains("VARCHAR", StringComparison.OrdinalIgnoreCase));
    }

    protected override DmlDefinition CreateInsertDml() => new DmlDefinition
    {
        Operation = "insert",
        TableName = TestTableName,
        Values = [
            new NameValuePair { Name = "NAME", Value = "David" },
            new NameValuePair { Name = "AGE", Value = 40 },
            new NameValuePair { Name = "ACTIVE", Value = 1 }
        ]
    };

    [Fact]
    public void BuildConnectionString_ShouldGenerateValidOracleFormat()
    {
        var model = new BuildDbConnectionModel
        {
            Provider = "Oracle",
            Host = "localhost",
            Port = "1521",
            Database = "xe",
            Username = "user",
            Password = "pw"
        };
        var connStr = Strategy.BuildConnectionString(model);

        var builder = new Oracle.ManagedDataAccess.Client.OracleConnectionStringBuilder(connStr);
        Assert.Contains("localhost:1521/xe", builder.DataSource);
        Assert.Equal("user", builder.UserID);
    }
}
