// <auto-generated />
using System;
using Admin.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Admin.Service.Data.Migrations
{
    [DbContext(typeof(AdminContext))]
    [Migration("20260730131839_AddStructuredAudit")]
    partial class AddStructuredAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Admin.Service.Data.Entites.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccessKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AffectedRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovalStatus")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DbManagementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Definition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCategory")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReturnedRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessKeyId");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DbManagementId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("ToolName");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Admin.Service.Data.Entites.CustomSqlTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomSqlTools");
                });

            modelBuilder.Entity("Admin.Service.Data.Entites.DbManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Database")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraSettings")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Port")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SqlProvider")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DbManagement");
                });

            modelBuilder.Entity("Admin.Service.Data.Entites.DbSemantic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColumnName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DbManagementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DbManagementId", "SchemaName", "TableName", "ColumnName")
                        .IsUnique();

                    b.ToTable("DbSemantics");
                });

            modelBuilder.Entity("Admin.Service.Data.Entites.McpAccessKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedTools")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorsAllowedOrigins")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DbManagementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SqlProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableWhitelist")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("KeyPrefix");

                    b.ToTable("McpAccessKeys");
                });

            modelBuilder.Entity("Admin.Service.Data.Entites.SecurityPolicySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowFullTableDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowFullTableUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DmlMaxAffectedRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IpPermitLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IpWindowSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyPermitLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyWindowSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConcurrentSql")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueryMaxRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueryTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireWhereForDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireWhereForUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SecurityPolicySettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowFullTableDelete = false,
                            AllowFullTableUpdate = false,
                            DmlMaxAffectedRows = 100,
                            IpPermitLimit = 60,
                            IpWindowSeconds = 60,
                            KeyPermitLimit = 120,
                            KeyWindowSeconds = 60,
                            MaxConcurrentSql = 16,
                            QueryMaxRows = 1000,
                            QueryTimeoutSeconds = 30,
                            RequireWhereForDelete = true,
                            RequireWhereForUpdate = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Admin.Service.Data.Entites.DbSemantic", b =>
                {
                    b.HasOne("Admin.Service.Data.Entites.DbManagement", "DbManagement")
                        .WithMany()
                        .HasForeignKey("DbManagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DbManagement");
                });
#pragma warning restore 612, 618
        }
    }
}
