// <auto-generated />
using System;
using Auth.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auth.Service.Data.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20260804121039_AddEnterpriseIdentity")]
    partial class AddEnterpriseIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Auth.Service.Data.Entites.AuthAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AuthActions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "view",
                            Name = "view"
                        },
                        new
                        {
                            Id = 2,
                            Code = "create",
                            Name = "create"
                        },
                        new
                        {
                            Id = 3,
                            Code = "edit",
                            Name = "edit"
                        },
                        new
                        {
                            Id = 4,
                            Code = "delete",
                            Name = "delete"
                        },
                        new
                        {
                            Id = 5,
                            Code = "revoke",
                            Name = "revoke"
                        });
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRefreshTokenHash")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("MemberId");

                    b.HasIndex("TokenFamilyId");

                    b.ToTable("AuthSessions");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.ExternalIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique();

                    b.ToTable("ExternalIdentities");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.ExternalLoginCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UsedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("MemberId");

                    b.ToTable("ExternalLoginCodes");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedSignInCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MfaSecretProtected")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedMail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequirePasswordChangeAtNextSignIn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecurityVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedMail")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.MemberRole", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemberId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("MemberRoles");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.MfaRecoveryCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UsedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "CodeHash")
                        .IsUnique();

                    b.ToTable("MfaRecoveryCodes");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("MemberId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Overview",
                            Path = "/home"
                        },
                        new
                        {
                            Id = 2,
                            Name = "MCP Keys",
                            Path = "/runtime/mcp-keys"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Custom Tools",
                            Path = "/runtime/custom-tools"
                        },
                        new
                        {
                            Id = 4,
                            Name = "DB Management",
                            Path = "/runtime/db-management"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Audit",
                            Path = "/runtime/audit"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Role Management",
                            Path = "/auth/role"
                        },
                        new
                        {
                            Id = 7,
                            Name = "User Management",
                            Path = "/auth/user"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Semantic Layer",
                            Path = "/runtime/db-management/semantic"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Security Policy",
                            Path = "/runtime/security"
                        });
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.PermissionAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId", "ActionId")
                        .IsUnique();

                    b.ToTable("PermissionActions");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.PermissionActionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("PermissionId", "ActionId")
                        .IsUnique();

                    b.ToTable("PermissionActionTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActionId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 3,
                            ActionId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 4,
                            ActionId = 5,
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 5,
                            ActionId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 6,
                            ActionId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 7,
                            ActionId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 8,
                            ActionId = 4,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 9,
                            ActionId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 10,
                            ActionId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 11,
                            ActionId = 3,
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 12,
                            ActionId = 4,
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 13,
                            ActionId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 14,
                            ActionId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 15,
                            ActionId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 16,
                            ActionId = 3,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 17,
                            ActionId = 4,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 18,
                            ActionId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 19,
                            ActionId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 20,
                            ActionId = 3,
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 21,
                            ActionId = 4,
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 22,
                            ActionId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 23,
                            ActionId = 3,
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 24,
                            ActionId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 25,
                            ActionId = 3,
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 26,
                            ActionId = 3,
                            PermissionId = 2
                        });
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.TokenBlacklistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.ToTable("TokenBlacklistEntries");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.AuthSession", b =>
                {
                    b.HasOne("Auth.Service.Data.Entites.Member", "Member")
                        .WithMany("AuthSessions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.ExternalIdentity", b =>
                {
                    b.HasOne("Auth.Service.Data.Entites.Member", "Member")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.ExternalLoginCode", b =>
                {
                    b.HasOne("Auth.Service.Data.Entites.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.MemberRole", b =>
                {
                    b.HasOne("Auth.Service.Data.Entites.Member", "Member")
                        .WithMany("MemberRoles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Service.Data.Entites.Role", "Role")
                        .WithMany("MemberRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.MfaRecoveryCode", b =>
                {
                    b.HasOne("Auth.Service.Data.Entites.Member", "Member")
                        .WithMany("MfaRecoveryCodes")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.PasswordResetToken", b =>
                {
                    b.HasOne("Auth.Service.Data.Entites.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.PermissionAction", b =>
                {
                    b.HasOne("Auth.Service.Data.Entites.AuthAction", "Action")
                        .WithMany("PermissionActions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Service.Data.Entites.Permission", "Permission")
                        .WithMany("PermissionActions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Service.Data.Entites.Role", "Role")
                        .WithMany("PermissionActions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.PermissionActionTemplate", b =>
                {
                    b.HasOne("Auth.Service.Data.Entites.AuthAction", "Action")
                        .WithMany("PermissionActionTemplates")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Service.Data.Entites.Permission", "Permission")
                        .WithMany("PermissionActionTemplates")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.AuthAction", b =>
                {
                    b.Navigation("PermissionActionTemplates");

                    b.Navigation("PermissionActions");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.Member", b =>
                {
                    b.Navigation("AuthSessions");

                    b.Navigation("ExternalIdentities");

                    b.Navigation("MemberRoles");

                    b.Navigation("MfaRecoveryCodes");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.Permission", b =>
                {
                    b.Navigation("PermissionActionTemplates");

                    b.Navigation("PermissionActions");
                });

            modelBuilder.Entity("Auth.Service.Data.Entites.Role", b =>
                {
                    b.Navigation("MemberRoles");

                    b.Navigation("PermissionActions");
                });
#pragma warning restore 612, 618
        }
    }
}
