<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

  <ItemGroup>
 	  <PackageReference Include="SqlKata" />
	  <PackageReference Include="SqlKata.Execution"/>
    <PackageReference Include="MySql.Data"/>
    <PackageReference Include="Npgsql"/>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="wwwroot\\**\\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
